### ISSUE TITLE
MySQL login information 

### ISSUE THREAD

**Issue by asimsharf** [supermavster/docker-laravel-8#10]
I Cant do the migration 
SQLSTATE[HY000] [1130] Host 'docker_laravel_artisan_run_5de336c01a78.docker_laravel_laravel' is not allowed to connect to this MySQL server (SQL: select * from information_schema.tables where table_schema = docker and table_name = migrations and table_type = 'BASE TABLE')

**Comment by JorgeLHS1** [comment]
Same thing happening to me, maybe is this new?

**Comment by asimsharf** [comment]
I fix it by removing the volumes inside docker-composer.yml
    # volumes:
    #   - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
    #   - dbdata:/var/lib/mysql/
