### ISSUE TITLE
Stoping artisan, npm, composer container

### ISSUE THREAD

**Issue by ramasofficial** [supermavster/docker-laravel-8#4]
Where can be a problem?

When i execute start all containers this containers working 10 seconds and shut downing.

![image](https://user-images.githubusercontent.com/36000935/103769485-0b674600-502d-11eb-9e67-b9afff7ab3be.png)

**Comment by JustinRijsdijk** [comment]
yeah, because you are not running commands for them ;)

**Comment by ramasofficial** [comment]
> yeah, because you are not running commands for them ;)

Yes, i know now, because this containers works in docker ram, i found a answer, before you write it, but thank you! :)

Close this issue.
